### ISSUE TITLE
Update for German locale for Clippings 5.5

### ISSUE THREAD

**Issue by Endor8** [aecreations/clippings#106]
Hi 
Since beta.babelzilla.org is not reachable, where  aim maintaining the German locale for clippings
so I uploaded it on my Github account:
https://github.com/Endor8/Erweiterungen/tree/master/Clippings
I also created a German localization of the File clippings6.xhtml
You can find it in the same folder.
Cheers
Endor

**Comment by aecreations** [comment]
Thank you very much Endor8!  I will include your contributions in version 5.5.2.

**Comment by aecreations** [comment]
Also added the updated .dtd and .properties files, commit  ea1ca8d

**Comment by Endor8** [comment]
Hi.
There was a big error in the German locale, in File *clippings.properties*
so please updated it ons more. Thanks and sorry.
Cheers
Endor

**Comment by aecreations** [comment]
The Mozilla Add-ons validator tool picked up that error, so I fixed it already.  But I will download your revision anyway and include it in the official 5.5.2 release.

I've uploaded Clippings 5.5.2 release candidate to the Mozilla Add-ons site, so feel free to install and test it.

**Comment by aecreations** [comment]
Fixed in Clippings 5.5.2

**Comment by aecreations** [comment]
@Endor8  - would you be available to help update the German translation of Clippings?  I'm working on Clippings 5.5.3, which updates a few UI strings due to Clippings 6 now available (and therefore no longer "coming soon").  Also added a proper error message when the upgrade to version 5.5.3 fails (for Firefox ESR 52 and Thunderbird users).

Clippings 6 isn't ready for translations yet... the UI strings need to be prepared for localization first before I can put out a call for translators.

If you're available to help out once again, that would be awesome.  Thanks in advance!

**Comment by Endor8** [comment]
Yes I have a look at it.

**Comment by Endor8** [comment]
This entity is still in the File clippings.dtd
<!ENTITY wxComing.desc "Clippings 6 is coming soon!  Click here to learn how to prepare for the upgrade.">

I saw the Error-message  in clippings.properties, the German locale is ready.
I use the 5.5.3b1 Version from here:
https://addons.mozilla.org/de/firefox/addon/clippings/versions/beta
for localisation. Is this the right one?

**Comment by aecreations** [comment]
Thanks @Endor8!  Please also review clippings6.xhtml... there were some changes due to Clippings 6 now being available, instead of "coming soon."

**Comment by Endor8** [comment]
Done! Sorry that I have forgotten to update this file.

**Comment by aecreations** [comment]
No problem. Thanks for doing this!
