### ISSUE TITLE
Error message shows repeatedly after update to 5.5.2

### ISSUE THREAD

**Issue by bfester** [aecreations/clippings#108]
![clippings_error](https://user-images.githubusercontent.com/10703/31896506-3e985348-b814-11e7-886a-4cf98c250fb9.png)

Shows on every Thunderbird and Firefox start and also on every new email.

**Comment by aecreations** [comment]
This error would occur if you do not have permissions to the Clippings datasource folder (which is typically your Firefox or Thunderbird profile folder, or a custom folder location if it was changed in extension preferences).

When running for the first time after the upgrade to version 5.5.x, Clippings renames the Clippings backup folder, located in the datasource folder, so that it is more visible to the user.  Because the folder permission is too restrictive, the first-run renaming fails, and this error will keep happening until the permissions on the datasource folder is changed.

**Comment by bfester** [comment]
Thank you. That solved the problem.
A better error message would probably be a good idea, to let the user know what's going on.
