### ISSUE TITLE
Save ordering of clippings and folders in the Synced Clippings folder

### ISSUE THREAD

**Issue by RW-CarlH** [aecreations/clippings#227]
Clippings 6.1b1

When syncing clippings to a new machine, all folders are again sorted to the top of the list.   The folders will stay put if moved on the new machine, but it would helpful not to have to re-do the ordering of folders among non-folder items each time a new machine starts syncing clippings.

**Comment by aecreations** [comment]
The `displayOrder` field of the synced clipping or folder from the Dexie database needs to be persisted in the JSON sync file as well.

**Comment by RW-CarlH** [comment]
Besides maintaining order in sync-clippings save and load, the same ordering or position loss also happens with the backup and restore feature in 6.1b1.

**Comment by aecreations** [comment]
Caveat: The display order of clippings and folders from from Thunderbird is not saved when exported from there. A fix similar to the above will need to be made to Clippings for Thunderbird Until that is fixed in Thunderbird, users who are syncing between Firefox and Thunderbird will notice that their ordering of clippings and folders are lost. This won't be an issue if syncing only between Firefox instances.
