### ISSUE TITLE
Clippings not syncing between different firefox profiles, 

### ISSUE THREAD

**Issue by pernicles** [aecreations/clippings#246]
I tried the new feature of clippings (which I think is an amazing idea) but when I installed the helper application clippings did not appear to sync the folder. I created the folder in Onedrive, and when I switched between Nightly and my person profile, there was no syncing being done. There are also no files in the synced folder.
![image](https://user-images.githubusercontent.com/45774567/49769203-e57fe380-fca4-11e8-9b1c-e7ee46426960.png)
![image](https://user-images.githubusercontent.com/45774567/49769273-2bd54280-fca5-11e8-8768-e2e57e3bd87b.png)
![image](https://user-images.githubusercontent.com/45774567/49769348-6c34c080-fca5-11e8-942f-ea4837b2ca29.png)
![image](https://user-images.githubusercontent.com/45774567/49769412-a0a87c80-fca5-11e8-8e3c-392ffeaffdc5.png)
![image](https://user-images.githubusercontent.com/45774567/49769474-f0874380-fca5-11e8-8535-238844f5cb27.png)
Also, could you edit the reload feature of sync? It is kind of annoying to have to click a dialog box instead of having it reload right away by clicking the reload arrow button. Thank you!

**Comment by aecreations** [comment]
The first screen shot shows that Sync Clippings is turned on in Clippings preferences - and yet, the About dialog shows that the helper app is "Not installed."  It looks like the helper app is not running on your system. Check that the Sync Clippings Helper isn't being blocked by an antivirus or anti-malware program.  You can also try uninstalling Sync Clippings Helper, then install it again, but making sure you have full admin rights in Windows when doing the reinstall.

**Comment by pernicles** [comment]
So, I reinstalled it with admin priviledges, and when I checked the about it said it was installed!
![image](https://user-images.githubusercontent.com/45774567/49882464-5256c300-fdf6-11e8-9b2f-74605cb73e49.png)
But when I turned Sync on, it said the app was not installed
![image](https://user-images.githubusercontent.com/45774567/49882534-71edeb80-fdf6-11e8-841d-c197ff1d5413.png)
The same thing happened with my personal profile in Firefox release version
![image](https://user-images.githubusercontent.com/45774567/49882665-b37e9680-fdf6-11e8-96ec-6999c1732723.png)
![image](https://user-images.githubusercontent.com/45774567/49882688-c002ef00-fdf6-11e8-858a-9263dcf7b7b2.png)
What do? The Sync feature is still not syncing. I pressed "Run anyway" when the windows screen protector prompted me to not run it, and I don't have any other anti-malware system installed.

**Comment by aecreations** [comment]
When you turned on Sync Clippings from Clippings preferences, a dialog box should have appeared with a textbox to specify the folder location of the sync folder on your system. Is that what you saw when you clicked Turn On Sync? What happens when you click OK to that dialog?  After Sync Clippings is turned on, there should be a "Settings..." button next to "Turn Off Sync"; when clicking on that, do you see the sync folder location populated in the textbox in the dialog that appears?

Try turning off Sync Clippings, then open the Browser Console in Firefox, clear out any log output to start fresh, then return to Clippings preferences and turn on Sync Clippings again. Are there any errors that appear in the Browser Console when turning on Sync Clippings? Copy and paste any console messages here.

Also, which version of Windows are you using?

**Comment by pernicles** [comment]
OOOOOOOOOOOOOOO shieeeeeet I think I got it working. The browser console had a error for Sync Clippings that said that the folder location did not exist, and I saw that when I copied and pasted the folder path it pasted with quotation marks, so I removed them and wallah.
![image](https://user-images.githubusercontent.com/45774567/49971754-279f6400-fef5-11e8-8448-d953b1ec9a36.png)
God bless you and your work. Thank you
